name: ECR-Deploy
on:
  workflow_dispatch:
    inputs:
      image_tag:
        type: string
        description: 'Image tag to deploy'
        required: true
        default: 'latest'
  push:
    branches:
      - master

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: aws credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
          aws-region: us-east-1


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build image to Amazon ECR
        id: build-image
        run: |
          docker build -t ecr-container-repo:latest .  # it is building the docker image

      - name: Tag to Amazon ECR
        run: docker tag ecr-container-repo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/ecr-container-repo:${{ github.event.inputs.image_tag }}

      
      - name: Push to Amazon ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/ecr-container-repo:${{ github.event.inputs.image_tag }}

      - name: setup kubectl
        run: |
          aws eks update-kubeconfig --name "my-eks-cluster"
          kubectl get pods --all-namespace

         


      





          



      